const CONTENT = {
  "js-basics": {
    headline: "JavaScript Fundamentals — Learn, code, practice",
    intro: "A structured beginner-friendly guide covering the JavaScript building blocks you need before React, Node.js and modern web development.",
    lessons: [
      { title: "Variables and Data Types", explanation: "Variables store values that your program can use and change. Prefer const when the binding should not be reassigned and let when it should. JavaScript has primitive values such as string, number, boolean, undefined, null, bigint and symbol, plus objects.", points: ["const prevents reassignment of the variable binding; object contents can still be changed.", "Use typeof to inspect many JavaScript values.", "Choose descriptive variable names so code remains readable."], code: "const name = 'Sibi';\nlet score = 85;\nconst passed = score >= 40;\n\nconsole.log(name, score, passed);", output: "Sibi 85 true", practice: ["Create variables for your name, age and college.", "Predict the result of typeof 42, typeof '42' and typeof true."] },
      { title: "Operators and Control Flow", explanation: "Operators let you calculate, compare and combine values. Control-flow statements decide which code runs and how often it runs.", points: ["Use === and !== for strict comparisons.", "if/else handles decisions; switch is useful for matching a known set of cases.", "for and while loops repeat work while a condition remains true."], code: "const mark = 72;\n\nif (mark >= 90) {\n  console.log('A');\n} else if (mark >= 60) {\n  console.log('B');\n} else {\n  console.log('C');\n}", output: "B", practice: ["Write a program that prints whether a number is even or odd.", "Use a loop to print numbers from 1 to 10."] },
      { title: "Functions", explanation: "Functions package reusable logic. They can accept parameters and return a value. Understanding parameters, return values and function scope is essential for writing maintainable JavaScript.", points: ["A function can be declared once and called many times.", "return sends a value back to the caller.", "Arrow functions provide a concise syntax and are common in modern JavaScript."], code: "function add(a, b) {\n  return a + b;\n}\n\nconst multiply = (a, b) => a * b;\n\nconsole.log(add(4, 6));\nconsole.log(multiply(4, 6));", output: "10\n24", practice: ["Create a function that returns the largest of two numbers.", "Write an arrow function that calculates the square of a number."] },
      { title: "Scope and Hoisting", explanation: "Scope determines where a variable can be accessed. let and const are block scoped, while var is function scoped. Hoisting explains why declarations can appear to be processed before their line in source code; it does not mean every variable is safely usable before declaration.", points: ["Prefer let and const over var in modern code.", "The temporal dead zone applies to let and const before initialization.", "Keep variables close to where they are used to reduce confusion."], code: "function demo() {\n  if (true) {\n    let message = 'inside';\n    console.log(message);\n  }\n}\n\ndemo();", output: "inside", practice: ["Create a block and test whether a let variable is accessible outside it.", "Explain in your own words why using let/const is safer than relying on var."] },
      { title: "Arrays and Array Methods", explanation: "Arrays store ordered collections. Modern JavaScript provides methods that make common data transformations expressive and concise.", points: ["map creates a new array by transforming every element.", "filter keeps elements that satisfy a condition.", "forEach runs a function for each element but does not create a transformed array."], code: "const marks = [45, 72, 88, 31];\nconst passed = marks.filter(mark => mark >= 40);\nconst boosted = marks.map(mark => mark + 5);\n\nconsole.log(passed);\nconsole.log(boosted);", output: "[45, 72, 88]\n[50, 77, 93, 36]", practice: ["Use map to double every number in an array.", "Use filter to find numbers greater than 50."] },
      { title: "Objects", explanation: "Objects represent related data using key-value pairs. They are fundamental to JSON, APIs, React props and Node.js applications.", points: ["Properties can be accessed with dot or bracket notation.", "Methods are functions stored as object properties.", "Destructuring extracts selected properties into variables."], code: "const student = {\n  name: 'Arun',\n  mark: 82,\n  passed: true\n};\n\nconst { name, mark } = student;\nconsole.log(`${name}: ${mark}`);", output: "Arun: 82", practice: ["Create an object for a book with title, author and price.", "Destructure two properties from your object."] },
      { title: "ES6 Essentials", explanation: "ES6 introduced language features that are now standard in everyday JavaScript: let/const, arrow functions, template literals, destructuring, spread syntax and more.", points: ["Template literals make string interpolation easy.", "Spread syntax is useful for copying and combining arrays or objects.", "Destructuring makes data extraction concise."], code: "const user = { name: 'Maya', role: 'Developer' };\nconst updated = { ...user, role: 'Frontend Developer' };\nconsole.log(`${updated.name} is a ${updated.role}`);", output: "Maya is a Frontend Developer", practice: ["Combine two arrays using spread syntax.", "Use a template literal to print a person's name and age."] },
      { title: "DOM and Events", explanation: "The Document Object Model lets JavaScript read and change a web page. Events allow your program to respond to user actions such as clicks, typing and form submission.", points: ["querySelector selects the first element matching a CSS selector.", "textContent changes text safely.", "addEventListener attaches behavior without mixing JavaScript directly into HTML."], code: "const button = document.querySelector('#save');\nconst message = document.querySelector('#message');\n\nbutton.addEventListener('click', () => {\n  message.textContent = 'Saved!';\n});", output: "Clicking #save changes the message to Saved!", practice: ["Create a button that changes a heading when clicked.", "Build a small counter with + and - buttons."] }
    ],
    checklist: ["Explain let, const and common data types.", "Write functions using normal and arrow syntax.", "Use map, filter and forEach correctly.", "Read and update object properties.", "Manipulate a DOM element and respond to a click event."] ,
    resources: [
      { title: "GeeksforGeeks — JavaScript Tutorial", url: "https://www.geeksforgeeks.org/javascript/" },
      { title: "MDN — JavaScript Guide", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide" }
    ]
  },
  "js-async": {
    headline: "Modern JavaScript & Async Programming",
    intro: "Understand how JavaScript handles delayed work, network requests, modules and API failures.",
    lessons: [
      { title: "Callbacks and the Event Loop", explanation: "JavaScript runs application code on a single main thread while the runtime can coordinate timers, network work and other asynchronous operations. The event loop schedules callbacks when the call stack is ready.", code: "console.log('Start');\nsetTimeout(() => console.log('Later'), 0);\nconsole.log('End');", output: "Start\nEnd\nLater", practice: ["Explain why the timer callback does not print before End."] },
      { title: "Promises", explanation: "A Promise represents the eventual result of an asynchronous operation. It can be pending, fulfilled or rejected, and can be chained with then/catch/finally.", code: "Promise.resolve(10)\n  .then(value => value * 2)\n  .then(value => console.log(value))\n  .catch(error => console.error(error));", output: "20", practice: ["Create a Promise that resolves with a user name after a short delay."] },
      { title: "async/await", explanation: "async/await provides a readable way to consume Promises. Use try/catch when an awaited operation can reject.", code: "async function loadUser() {\n  try {\n    const response = await fetch('/api/user');\n    const user = await response.json();\n    console.log(user);\n  } catch (error) {\n    console.error(error);\n  }\n}", practice: ["Rewrite a Promise chain using async/await.", "Add a loading message before the request and remove it in finally-style cleanup."] },
      { title: "Fetch API and JSON", explanation: "fetch sends HTTP requests from browser JavaScript. A successful network response is not automatically a successful HTTP status, so check response.ok before reading the data.", code: "const response = await fetch('/api/courses');\nif (!response.ok) throw new Error('Request failed');\nconst courses = await response.json();", practice: ["Fetch a public JSON endpoint and display three fields from the response."] },
      { title: "Modules and API Error Handling", explanation: "ES modules let you split code into focused files using export and import. Good API code handles loading, success and error states explicitly.", code: "// math.js\nexport const double = n => n * 2;\n\n// app.js\nimport { double } from './math.js';\nconsole.log(double(8));", output: "16", practice: ["Create a utility module with two exported functions and import them into another file."] }
    ],
    checklist: ["Explain the event loop at a high level.", "Create and consume Promises.", "Use async/await with try/catch.", "Call an API with fetch and validate response.ok.", "Use import/export modules."] ,
    resources: [{ title: "GeeksforGeeks — JavaScript Asynchronous Programming", url: "https://www.geeksforgeeks.org/javascript/asynchronous-javascript/" }, { title: "MDN — Using Fetch", url: "https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch" }]
  },
  "react": {
    headline: "React Fundamentals",
    intro: "Build reusable interfaces by combining components, props, state, hooks and routing.",
    lessons: [
      { title: "JSX and Components", explanation: "JSX is a syntax extension that describes UI. Function components are JavaScript functions that return JSX.", code: "function Welcome({ name }) {\n  return <h2>Hello, {name}!</h2>;\n}\n\nexport default function App() {\n  return <Welcome name='Learner' />;\n}", output: "A reusable Welcome component renders Hello, Learner!", practice: ["Create a Profile component with name and role props."] },
      { title: "Props and Composition", explanation: "Props pass data from a parent to a child. Composition lets components be combined instead of creating one giant component.", code: "function Card({ title, children }) {\n  return <section><h3>{title}</h3>{children}</section>;\n}", practice: ["Build a reusable Card that accepts a title and arbitrary children."] },
      { title: "State and Events", explanation: "useState gives a component a value that persists between renders. Updating state schedules a new render.", code: "const [count, setCount] = useState(0);\n\n<button onClick={() => setCount(count + 1)}>\n  Count: {count}\n</button>", practice: ["Build a counter with increment, decrement and reset buttons."] },
      { title: "Forms and Conditional Rendering", explanation: "Controlled inputs keep form values in React state. Conditional rendering chooses what UI to show based on application state.", code: "const [name, setName] = useState('');\n\n<input value={name} onChange={e => setName(e.target.value)} />\n{name && <p>Welcome, {name}</p>}", practice: ["Create a login form with email and password state."] },
      { title: "useEffect and Routing", explanation: "useEffect is useful for synchronizing a component with external systems such as fetching data. React Router maps URLs to components for multi-page-like navigation in a single-page application.", code: "useEffect(() => {\n  fetch('/api/courses')\n    .then(r => r.json())\n    .then(setCourses);\n}, []);", practice: ["Create Home and About routes and navigate between them."] }
    ],
    checklist: ["Create function components.", "Pass and read props.", "Manage state with useState.", "Handle forms and events.", "Use useEffect and basic routing."] ,
    resources: [{ title: "GeeksforGeeks — React Tutorial", url: "https://www.geeksforgeeks.org/reactjs-tutorials/" }, { title: "React — Learn", url: "https://react.dev/learn" }]
  },
  "node": {
    headline: "Node.js & Express", intro: "Learn the server-side JavaScript skills needed to create REST APIs and backend applications.",
    lessons: [
      { title: "Node.js Runtime and npm", explanation: "Node.js runs JavaScript outside the browser. npm manages packages and project metadata through package.json.", code: "npm init -y\nnpm install express", practice: ["Create a Node project and inspect its package.json."] },
      { title: "Express Server", explanation: "Express provides a lightweight routing and middleware layer for Node.js HTTP applications.", code: "import express from 'express';\nconst app = express();\n\napp.get('/', (req, res) => {\n  res.json({ message: 'Hello API' });\n});\n\napp.listen(5000);", output: "GET / returns a JSON response.", practice: ["Create a /health route that returns { status: 'ok' }."] },
      { title: "Routes and Middleware", explanation: "Routes decide which handler responds to a request. Middleware can inspect or modify requests and responses before the route runs.", code: "app.use(express.json());\n\napp.use((req, res, next) => {\n  console.log(req.method, req.url);\n  next();\n});", practice: ["Write middleware that logs the current timestamp for every request."] },
      { title: "REST Endpoints", explanation: "A REST API commonly maps HTTP methods to operations on resources: GET for reading, POST for creating, PUT/PATCH for updating and DELETE for removal.", code: "app.post('/api/users', (req, res) => {\n  const user = req.body;\n  res.status(201).json(user);\n});", practice: ["Design GET, POST, PUT and DELETE routes for a notes resource."] },
      { title: "Validation and Errors", explanation: "Production APIs should validate input and return meaningful HTTP status codes instead of exposing internal errors.", code: "app.use((err, req, res, next) => {\n  console.error(err);\n  res.status(500).json({ error: 'Internal server error' });\n});", practice: ["Add validation that rejects a user creation request without an email."] }
    ],
    checklist: ["Initialize a Node project.", "Create Express routes.", "Understand middleware.", "Design REST endpoints.", "Handle validation and errors."] ,
    resources: [{ title: "GeeksforGeeks — Node.js Tutorial", url: "https://www.geeksforgeeks.org/nodejs/" }, { title: "Express — Getting Started", url: "https://expressjs.com/en/starter/installing.html" }]
  },
  "mongodb": {
    headline: "MongoDB Essentials", intro: "Work with documents, collections, CRUD operations, indexes and Node.js integration.",
    lessons: [
      { title: "Documents and Collections", explanation: "MongoDB is a document database. Documents are JSON-like records stored inside collections, making it convenient for application data that evolves over time.", code: "{\n  name: 'Asha',\n  course: 'JavaScript',\n  progress: 72\n}", practice: ["Design a document for a learner with name, skills and completedCourses."] },
      { title: "CRUD Operations", explanation: "CRUD means create, read, update and delete. MongoDB exposes methods such as insertOne, find, updateOne and deleteOne.", code: "db.students.insertOne({ name: 'Asha', mark: 82 });\ndb.students.find({ mark: { $gte: 80 } });", practice: ["Insert three students and query students with marks above 70."] },
      { title: "Queries and Filtering", explanation: "Query operators let you express conditions such as greater than, inclusion and logical combinations.", code: "db.courses.find({\n  duration: { $lte: 3 },\n  skills: { $in: ['JavaScript'] }\n});", practice: ["Find learners whose progress is between 50 and 90."] },
      { title: "Indexes and Performance", explanation: "Indexes speed up frequently used queries by creating an optimized lookup structure. They also consume storage and can add write overhead, so index deliberately.", code: "db.students.createIndex({ email: 1 });\ndb.students.find({ email: 'a@example.com' });", practice: ["Identify which field in a student collection would benefit from a unique index."] },
      { title: "Mongoose Integration", explanation: "Mongoose provides schemas, models and validation for MongoDB applications built with Node.js.", code: "const Student = mongoose.model('Student', {\n  name: String,\n  mark: Number\n});", practice: ["Create a Mongoose model for a course with title, level and duration."] }
    ],
    checklist: ["Explain documents and collections.", "Perform CRUD operations.", "Write filtered queries.", "Explain why indexes help.", "Create a basic Mongoose model."] ,
    resources: [{ title: "GeeksforGeeks — MongoDB Tutorial", url: "https://www.geeksforgeeks.org/mongodb-tutorial/" }, { title: "MongoDB — CRUD Operations", url: "https://www.mongodb.com/docs/manual/crud/" }]
  },
  "python-basics": {
    headline: "Python Programming Basics", intro: "Build a strong Python foundation for automation, data analysis and machine learning.",
    lessons: [
      { title: "Syntax, Variables and Types", explanation: "Python uses indentation to define blocks and has dynamic typing. Common built-in types include int, float, str, bool, list, tuple, set and dict.", code: "name = 'Sibi'\nage = 19\nscore = 87.5\npassed = True\nprint(name, age, score, passed)", output: "Sibi 19 87.5 True", practice: ["Create variables for a product name, price and stock count."] },
      { title: "Conditionals and Loops", explanation: "Use if/elif/else for decisions and for/while loops for repetition. Python's range function is commonly used for counted loops.", code: "for mark in [35, 72, 91]:\n    if mark >= 40:\n        print('Pass')\n    else:\n        print('Fail')", output: "Fail\nPass\nPass", practice: ["Print all even numbers from 1 to 20."] },
      { title: "Functions", explanation: "Functions are defined with def and can accept parameters and return values. Default arguments make common cases convenient.", code: "def greet(name='Learner'):\n    return f'Hello, {name}!'\n\nprint(greet('Asha'))", output: "Hello, Asha!", practice: ["Write a function that returns the average of three numbers."] },
      { title: "Collections", explanation: "Lists are ordered and mutable, tuples are ordered and immutable, sets store unique values, and dictionaries store key-value pairs.", code: "student = {'name': 'Asha', 'mark': 82}\nprint(student['name'])\n\nskills = ['Python', 'SQL', 'Python']\nprint(set(skills))", output: "Asha\n{'Python', 'SQL'}", practice: ["Create a dictionary for a course and update one field."] },
      { title: "Files", explanation: "Use open with a context manager to safely read or write files. The with statement closes the file automatically.", code: "with open('notes.txt', 'w') as file:\n    file.write('Learn Python\n')\n\nwith open('notes.txt') as file:\n    print(file.read())", output: "Learn Python", practice: ["Write five lines to a file and read them back."] }
    ],
    checklist: ["Write valid Python syntax.", "Use conditions and loops.", "Define and call functions.", "Choose the right collection type.", "Read and write files safely."] ,
    resources: [{ title: "GeeksforGeeks — Python Programming Language", url: "https://www.geeksforgeeks.org/python-programming-language-tutorial/" }, { title: "Python — Official Tutorial", url: "https://docs.python.org/3/tutorial/" }]
  },
  "ml-foundations": {
    headline: "Machine Learning Foundations", intro: "Understand the complete ML workflow from data preparation to model evaluation.",
    lessons: [
      { title: "What is Machine Learning?", explanation: "Machine learning uses data to learn patterns that can support predictions or decisions. Supervised learning uses labeled targets; unsupervised learning looks for structure without target labels.", code: "from sklearn.model_selection import train_test_split\n\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)", practice: ["Give one example of a supervised problem and one unsupervised problem."] },
      { title: "Data Cleaning and EDA", explanation: "Real datasets often contain missing values, inconsistent types and outliers. Exploratory data analysis helps you understand distributions, relationships and suspicious records before modeling.", code: "df = df.drop_duplicates()\ndf['age'] = df['age'].fillna(df['age'].median())\nprint(df.describe())", practice: ["Inspect a dataset for missing values and duplicate rows."] },
      { title: "Regression and Feature Engineering", explanation: "Regression predicts continuous values. Feature engineering transforms raw data into useful model inputs, while scaling can be important for distance- or gradient-based methods.", code: "from sklearn.linear_model import LinearRegression\nmodel = LinearRegression()\nmodel.fit(X_train, y_train)\npredictions = model.predict(X_test)", practice: ["Choose features for a house-price prediction problem and explain why."] },
      { title: "Classification and Overfitting", explanation: "Classification predicts categories. Overfitting happens when a model learns training-specific patterns that do not generalize well to unseen data.", code: "from sklearn.linear_model import LogisticRegression\nmodel = LogisticRegression(max_iter=1000)\nmodel.fit(X_train, y_train)", practice: ["Explain one way to reduce overfitting."] },
      { title: "Evaluation and Cross-Validation", explanation: "Accuracy alone can be misleading, especially with imbalanced classes. Precision, recall and F1 provide additional views of classification performance. Cross-validation tests stability across multiple train/validation splits.", code: "from sklearn.metrics import accuracy_score, f1_score\n\nprint(accuracy_score(y_test, predictions))\nprint(f1_score(y_test, predictions))", practice: ["Choose an evaluation metric for a fraud-detection classifier and justify it."] }
    ],
    checklist: ["Distinguish supervised and unsupervised learning.", "Clean and explore a dataset.", "Prepare features and train a baseline model.", "Recognize overfitting.", "Select suitable evaluation metrics."] ,
    resources: [{ title: "GeeksforGeeks — Machine Learning", url: "https://www.geeksforgeeks.org/machine-learning/" }, { title: "scikit-learn — User Guide", url: "https://scikit-learn.org/stable/user_guide.html" }]
  },
  "mern-project": { headline: "MERN Full-Stack Project Guide", intro: "A practical project path for turning your React, Node.js and MongoDB knowledge into a deployable application.", lessons: [
    { title: "Plan the Product", explanation: "Define the users, core problem, screens, data entities and minimum viable feature set before writing code.", practice: ["Write a one-page specification for a student task manager.", "Draw the main screens and data relationships."] },
    { title: "Build the Backend", explanation: "Create the Express API, connect MongoDB, validate requests and implement authentication or authorization if your project needs accounts.", practice: ["Create CRUD endpoints for one main resource.", "Test every endpoint with valid and invalid input."] },
    { title: "Connect React to the API", explanation: "Create reusable UI components, manage loading/error states and call your API from the frontend.", practice: ["Build a list page, create form and edit form connected to the backend."] },
    { title: "Test and Deploy", explanation: "Test the complete flow, handle edge cases, protect secrets with environment variables and deploy the frontend and backend separately or together.", practice: ["Create a deployment checklist and test the production API from the live frontend."] }
  ], checklist: ["A working React frontend", "REST API with validation", "MongoDB persistence", "Clear README and screenshots", "Deployed application"], resources: [{ title: "GeeksforGeeks — MERN Stack", url: "https://www.geeksforgeeks.org/mern/" }] },
  "ml-project": { headline: "ML Prediction Project Guide", intro: "Follow a reproducible end-to-end machine learning workflow.", lessons: [
    { title: "Frame the Problem", explanation: "Define the target, input features, success metric and what a useful prediction means for the user.", practice: ["Write the problem statement and target variable for a prediction dataset."] },
    { title: "Prepare Data", explanation: "Clean missing values, inspect outliers, encode categories and split data without leaking test information into training.", practice: ["Document every preprocessing decision in your notebook."] },
    { title: "Train a Baseline", explanation: "Start with a simple model before tuning complex alternatives. Record the metric and configuration so comparisons are meaningful.", practice: ["Train at least two models and compare them using the same validation strategy."] },
    { title: "Evaluate and Document", explanation: "Interpret metrics, inspect errors and explain limitations. A good ML project communicates what the model can and cannot do.", practice: ["Create a final report with dataset, preprocessing, model, metrics and conclusions."] }
  ], checklist: ["Defined prediction target", "Clean train/test workflow", "Baseline model", "Evaluation metrics", "Documented findings"], resources: [{ title: "GeeksforGeeks — Machine Learning Projects", url: "https://www.geeksforgeeks.org/machine-learning-projects/" }] },
  "student-performance-project": { headline: "Student Performance Prediction Project", intro: "Build a portfolio-ready ML project using attendance, grades and study-related features.", lessons: [
    { title: "Explore the Dataset", explanation: "Inspect columns, distributions and correlations. Identify which variables could plausibly contribute to academic performance.", practice: ["Create three visualizations that reveal useful patterns in the data."] },
    { title: "Prepare Features", explanation: "Handle missing values, encode categorical variables and choose features without accidentally using information that would only be known after the prediction time.", practice: ["Explain why each selected feature is appropriate."] },
    { title: "Train and Evaluate", explanation: "Train a regression or classification model depending on your target. Compare predictions with appropriate metrics.", practice: ["Compare a simple baseline with a second model."] },
    { title: "Communicate Results", explanation: "Summarize important factors, model performance and limitations in a short report suitable for a portfolio.", practice: ["Write a five-sentence executive summary of your findings."] }
  ], checklist: ["Cleaned student dataset", "Feature selection", "Trained model", "Evaluation report", "Portfolio-ready README"], resources: [{ title: "GeeksforGeeks — Machine Learning Projects", url: "https://www.geeksforgeeks.org/machine-learning-projects/" }] },
  "ai-chatbot-project": { headline: "AI Learning Chatbot Project Guide", intro: "Design a chatbot that answers learner questions and gives useful study guidance.", lessons: [
    { title: "Conversation Design", explanation: "List common learner intents such as explaining a topic, generating practice questions and suggesting what to study next.", practice: ["Write 20 realistic learner questions and group them into intents."] },
    { title: "Response Engine", explanation: "Start with a small deterministic or retrieval-based prototype before adding more advanced ML. Keep responses grounded in your available learning content.", practice: ["Implement intent matching for at least five intents."] },
    { title: "Learning Guidance", explanation: "Use learner progress, assessment results and topic prerequisites to make recommendations rather than giving generic answers.", practice: ["Design three rules that choose a next topic based on assessment score and progress."] },
    { title: "Test and Improve", explanation: "Test unclear, incomplete and out-of-scope questions. Track failure cases and improve the system based on real examples.", practice: ["Create a test set of 30 questions and measure how many receive useful responses."] }
  ], checklist: ["Intent list", "Response system", "Learning recommendations", "Out-of-scope handling", "Test dataset"], resources: [{ title: "GeeksforGeeks — Chatbot", url: "https://www.geeksforgeeks.org/chatbots-using-python/" }] }
};

export function getCourseContent(id) {
  return CONTENT[id] || null;
}

export default CONTENT;
